//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 21-05-2025 10:06:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Xml.Linq;

namespace BD.PublicPortal.Core.Entities.Enums
{
    public enum DonorAvailability : int
    {
        [Display(Name="Matin")]
        Morning = 1,
        [Display(Name = "Après Midi")]
        Afternoon = 2,
        [Display(Name = "La journee")]
        Day = 3,
        [Display(Name = "Le Soir")]
        Night = 4,
        [Display(Name = "A Tout Moment")]
        AllTime = 5
    }
}
