# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=57679


// List all contributors
GET {{host}}:{{port}}/Contributors

###
// Get a specific contributor
@id_to_get=2
GET {{host}}:{{port}}/Contributors/{{id_to_get}}

###
// Add a new contributor
POST {{host}}:{{port}}/Contributors
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "test@test.com",
  "phoneNumber": "1234567890"
}

###
// Update a contributor
@id_to_update=3
PUT {{host}}:{{port}}/Contributors/{{id_to_update}}
Content-Type: application/json

{
  "id": {{id_to_update}},
  "name": "ardalis2"
}

###
// Delete a contributor
@id_to_delete=6
DELETE {{host}}:{{port}}/Contributors/{{id_to_delete}}

###



//********************************************************************//********************************************************************

GET {{host}}:{{port}}/enums/BloodGroup,DonorAvailability,DonorContactMethod

###
GET {{host}}:{{port}}/Wilayas

###
GET {{host}}:{{port}}/Communes/44

###
GET {{host}}:{{port}}/BTC/32

###
GET {{host}}:{{port}}/BloodDonationRequests

### Register a new user
POST {{host}}:{{port}}/auth/register2
Content-Type: application/json
{
  "userName": "walidozich",
  "email": "walidozich@example.com",
  "password": "vV@L1d@2002",
  "confirmPassword": "vV@L1d@2002",
  "donorWantToStayAnonymous": true,
  "donorExcludeFromPublicPortal": false,
  "donorAvailability": 1,
  "donorContactMethod": 1,
  "donorName": "CHERCHALI WALID",
  "donorBirthDate": "2025-05-22T09:16:16.749Z",
  "donorBloodGroup": 7,
  "donorNIN": "123456789123456789",
  "donorTel": "05.55.05.23.76",
  "donorNotesForBTC": "Je suis Diabétique Type 1",
  "donorLastDonationDate": "2025-05-22T09:16:16.749Z",
  "communeId": 558  
}

###
POST {{host}}:{{port}}/auth/register2
Content-Type: application/json
{
  "userName": "chk",
  "email": "chk@example.com",
  "password": "Karim-74",
  "confirmPassword": "Karim-74",
  "donorName": "CHERCHALI KARIM",
  "donorBirthDate": "2025-05-22T09:16:16.749Z",
  "donorBloodGroup": 7,
  "donorNIN": "123456789123456789"  
}

###
POST {{host}}:{{port}}/auth/login
Content-Type: application/json
{
  "email": "chk",
  "password": "Karim-74"
}

###
@token = CfDJ8L42nD5MPzlJlHz_DbJr-S1RrWyraV7PmKE26GD-o896apRBDYK1xOQkJSBtggDxZT9mrZR-O_p4MsSWP6MN7eI6qImQ-XUaU2jD4g1IdphqFaecSRbcLnnRB7UDnVz-9f9QmY_bgFiBs-r_jRNeU50DmkJTYqdH-Kzzqmb0Ppj7xfdS16hIvvA7z7DyjStLtNnd9cX5MMLjWYePK-pD-FaKPMNtLj8uXHYPJpX7C2IRd2tVlt0CdtZThIQiqed8TKkv2gJiyJODY9NN41rFejCryTmV-fnqb6zf9bomQqu7TkiSrgHHHdoY6kS62Q2SO3cXZz6yUjeumCx6qykvT66ZGUfoZgl2jyuZGsRHsr3UkDxVK49HOlgU-6kssHWO47aiMcN9TB2fVy1w6c3OxOmdMMdTnx6cmjKJChMoDWj1y4YB4W2zX646DN_MsGQhmIb2rgxC2OkX7jvpAVIGl2UaUDyqk_HmXXlKtT1pVK8shvtt7IZ7EAXTEcAZiiVe7PctDy1_rmrISrlc_i0Dg1kMWP9kQ1_UVVNtfrcMBlkyWn419d70IkuAq0pdAicI9WdU2gWsySzvZhuf8tKcKROep9jTkGfo1tC7MfScz0a8WTUhzqT6k11zy9nleSwNMe7N3TThQumQV3CBW9kmNz1znaCWxIhXtFdVlsn9Dk5EwyY0U81Je-c7J5_EWeOFAA
GET {{host}}:{{port}}/auth/manage/info
Authorization: Bearer {{token}}

